// Package po
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package po

import (
	datatypes "gorm.io/datatypes"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// UserRegEmail ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户注册邮箱'
type UserRegEmail struct {
	Id          uint64    `gorm:"column:id;primaryKey" json:"id"`          // ID
	CreatedTime time.Time `gorm:"column:created_time" json:"created_time"` // 创建时间
	UpdatedTime time.Time `gorm:"column:updated_time" json:"updated_time"` // 最后修改时间
	DeletedTime uint64    `gorm:"column:deleted_time" json:"deleted_time"` // 删除时间
	UserId      uint64    `gorm:"column:user_id" json:"user_id"`           // uid
	UserEmail   string    `gorm:"column:user_email" json:"user_email"`     // 邮箱
}
