// Package data
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package data

import (
	"bytes"
	context "context"
	"github.com/go-micro-saas/user-service/app/user-service/internal/data/po"
	datarepos "github.com/go-micro-saas/user-service/app/user-service/internal/data/repo"
	schemas "github.com/go-micro-saas/user-service/app/user-service/internal/data/schema/uid_user"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
	errorpkg "github.com/ikaiguang/go-srv-kit/kratos/error"
	gorm "gorm.io/gorm"
	"strings"
)

// userRepo repo
type userRepo struct {
	dbConn     *gorm.DB     // *gorm.DB
	UserSchema schemas.User // User
}

// NewUserRepo new data repo
func NewUserRepo(dbConn *gorm.DB) datarepos.UserDataRepo {
	return &userRepo{
		dbConn: dbConn,
	}
}

// =============== 创建 ===============

// create insert one
func (s *userRepo) create(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Create(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Create insert one
func (s *userRepo) Create(ctx context.Context, dataModel *po.User) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *userRepo) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) error {
	return s.create(ctx, dbConn, dataModel)
}

// existCreate exist create
func (s *userRepo) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (anotherModel *po.User, isNotFound bool, err error) {
	anotherModel = new(po.User)
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *userRepo) ExistCreate(ctx context.Context, dataModel *po.User) (anotherModel *po.User, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

// ExistCreateWithDBConn exist create
func (s *userRepo) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (anotherModel *po.User, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *userRepo) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*po.User, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// CreateInBatches create many
func (s *userRepo) CreateInBatches(ctx context.Context, dataModels []*po.User, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *userRepo) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.User, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *userRepo) update(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		// Where(schemas.FieldId+" = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Update update
func (s *userRepo) Update(ctx context.Context, dataModel *po.User) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *userRepo) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) error {
	return s.update(ctx, dbConn, dataModel)
}

// existUpdate exist update
func (s *userRepo) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (anotherModel *po.User, isNotFound bool, err error) {
	anotherModel = new(po.User)
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		Where(schemas.FieldId+" != ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *userRepo) ExistUpdate(ctx context.Context, dataModel *po.User) (anotherModel *po.User, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *userRepo) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (anotherModel *po.User, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

// =============== query one : 查一个 ===============

// queryOneById query one by id
func (s *userRepo) queryOneById(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *po.User, isNotFound bool, err error) {
	dataModel = new(po.User)
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where(schemas.FieldId+" = ?", id).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneById query one by id
func (s *userRepo) QueryOneById(ctx context.Context, id interface{}) (dataModel *po.User, isNotFound bool, err error) {
	return s.queryOneById(ctx, s.dbConn, id)
}

// QueryOneByIdWithDBConn query one by id
func (s *userRepo) QueryOneByIdWithDBConn(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *po.User, isNotFound bool, err error) {
	return s.queryOneById(ctx, dbConn, id)
}

// queryOneByConditions query one by conditions
func (s *userRepo) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.User, isNotFound bool, err error) {
	dataModel = new(po.User)
	dbConn = dbConn.WithContext(ctx).Table(s.UserSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *userRepo) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.User, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *userRepo) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.User, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *userRepo) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*po.User, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.UserSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *userRepo) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*po.User, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *userRepo) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*po.User, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *userRepo) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.User, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.UserSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormpkg.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormpkg.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormpkg.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// List 列表
func (s *userRepo) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.User, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *userRepo) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.User, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

// =============== delete : 删除 ===============

// delete delete one
func (s *userRepo) delete(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		Delete(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// Delete delete one
func (s *userRepo) Delete(ctx context.Context, dataModel *po.User) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *userRepo) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.User) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *userRepo) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.UserSchema.TableName()).
		Where(schemas.FieldId+" in (?)", ids).
		Delete(po.User{}).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *userRepo) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *userRepo) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormpkg.BatchInsertRepo = new(UserSlice)

// UserSlice 表切片
type UserSlice []*po.User

// TableName 表名
func (s *UserSlice) TableName() string {
	return schemas.UserSchema.TableName()
}

// Len 长度
func (s *UserSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *UserSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime, schemas.FieldUpdatedTime,
		schemas.FieldDeletedTime, schemas.FieldUserId,
		schemas.FieldUserPhone, schemas.FieldUserEmail,
		schemas.FieldUserNickname, schemas.FieldUserAvatar,
		schemas.FieldUserGender, schemas.FieldRegisterType,
		schemas.FieldUserStatus, schemas.FieldDisableTime,
		schemas.FieldBlacklistTime, schemas.FieldPasswordHash,
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *UserSlice) InsertValues(args *gormpkg.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].DeletedTime)
		prepareData = append(prepareData, dataModels[index].UserId)
		prepareData = append(prepareData, dataModels[index].UserPhone)
		prepareData = append(prepareData, dataModels[index].UserEmail)
		prepareData = append(prepareData, dataModels[index].UserNickname)
		prepareData = append(prepareData, dataModels[index].UserAvatar)
		prepareData = append(prepareData, dataModels[index].UserGender)
		prepareData = append(prepareData, dataModels[index].RegisterType)
		prepareData = append(prepareData, dataModels[index].UserStatus)
		prepareData = append(prepareData, dataModels[index].DisableTime)
		prepareData = append(prepareData, dataModels[index].BlacklistTime)
		prepareData = append(prepareData, dataModels[index].PasswordHash)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *UserSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime + "=excluded." + schemas.FieldCreatedTime,
		schemas.FieldUpdatedTime + "=excluded." + schemas.FieldUpdatedTime,
		schemas.FieldDeletedTime + "=excluded." + schemas.FieldDeletedTime,
		schemas.FieldUserId + "=excluded." + schemas.FieldUserId,
		schemas.FieldUserPhone + "=excluded." + schemas.FieldUserPhone,
		schemas.FieldUserEmail + "=excluded." + schemas.FieldUserEmail,
		schemas.FieldUserNickname + "=excluded." + schemas.FieldUserNickname,
		schemas.FieldUserAvatar + "=excluded." + schemas.FieldUserAvatar,
		schemas.FieldUserGender + "=excluded." + schemas.FieldUserGender,
		schemas.FieldRegisterType + "=excluded." + schemas.FieldRegisterType,
		schemas.FieldUserStatus + "=excluded." + schemas.FieldUserStatus,
		schemas.FieldDisableTime + "=excluded." + schemas.FieldDisableTime,
		schemas.FieldBlacklistTime + "=excluded." + schemas.FieldBlacklistTime,
		schemas.FieldPasswordHash + "=excluded." + schemas.FieldPasswordHash,
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *UserSlice) ConflictActionForMySQL() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *UserSlice) ConflictActionForPostgres() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *userRepo) insert(ctx context.Context, dbConn *gorm.DB, dataModels UserSlice) error {
	err := gormpkg.BatchInsertWithContext(ctx, dbConn, &dataModels)
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return nil
}

// Insert 批量插入
func (s *userRepo) Insert(ctx context.Context, dataModels []*po.User) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *userRepo) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.User) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *userRepo) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	// tableName := s.UserSchema.TableName()

	// On-demand loading

	// id
	// if data, ok := conditions[schemas.FieldId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldId+" = ?", data)
	// }

	// created_time
	// if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldCreatedTime+" = ?", data)
	// }

	// updated_time
	// if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUpdatedTime+" = ?", data)
	// }

	// deleted_time
	// if data, ok := conditions[schemas.FieldDeletedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldDeletedTime+" = ?", data)
	// }

	// user_id
	// if data, ok := conditions[schemas.FieldUserId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserId+" = ?", data)
	// }

	// user_phone
	// if data, ok := conditions[schemas.FieldUserPhone]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserPhone+" = ?", data)
	// }

	// user_email
	// if data, ok := conditions[schemas.FieldUserEmail]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserEmail+" = ?", data)
	// }

	// user_nickname
	// if data, ok := conditions[schemas.FieldUserNickname]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserNickname+" = ?", data)
	// }

	// user_avatar
	// if data, ok := conditions[schemas.FieldUserAvatar]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserAvatar+" = ?", data)
	// }

	// user_gender
	// if data, ok := conditions[schemas.FieldUserGender]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserGender+" = ?", data)
	// }

	// register_type
	// if data, ok := conditions[schemas.FieldRegisterType]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldRegisterType+" = ?", data)
	// }

	// user_status
	// if data, ok := conditions[schemas.FieldUserStatus]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUserStatus+" = ?", data)
	// }

	// disable_time
	// if data, ok := conditions[schemas.FieldDisableTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldDisableTime+" = ?", data)
	// }

	// blacklist_time
	// if data, ok := conditions[schemas.FieldBlacklistTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldBlacklistTime+" = ?", data)
	// }

	// password_hash
	// if data, ok := conditions[schemas.FieldPasswordHash]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldPasswordHash+" = ?", data)
	// }

	return dbConn
}

// UpdateColumns update columns
func (s *userRepo) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// id
	//if data, ok := conditions[schemas.FieldId]; ok {
	//	updateColumns[schemas.FieldId] = data
	//}

	// created_time
	//if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	//	updateColumns[schemas.FieldCreatedTime] = data
	//}

	// updated_time
	//if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	//	updateColumns[schemas.FieldUpdatedTime] = data
	//}

	// deleted_time
	//if data, ok := conditions[schemas.FieldDeletedTime]; ok {
	//	updateColumns[schemas.FieldDeletedTime] = data
	//}

	// user_id
	//if data, ok := conditions[schemas.FieldUserId]; ok {
	//	updateColumns[schemas.FieldUserId] = data
	//}

	// user_phone
	//if data, ok := conditions[schemas.FieldUserPhone]; ok {
	//	updateColumns[schemas.FieldUserPhone] = data
	//}

	// user_email
	//if data, ok := conditions[schemas.FieldUserEmail]; ok {
	//	updateColumns[schemas.FieldUserEmail] = data
	//}

	// user_nickname
	//if data, ok := conditions[schemas.FieldUserNickname]; ok {
	//	updateColumns[schemas.FieldUserNickname] = data
	//}

	// user_avatar
	//if data, ok := conditions[schemas.FieldUserAvatar]; ok {
	//	updateColumns[schemas.FieldUserAvatar] = data
	//}

	// user_gender
	//if data, ok := conditions[schemas.FieldUserGender]; ok {
	//	updateColumns[schemas.FieldUserGender] = data
	//}

	// register_type
	//if data, ok := conditions[schemas.FieldRegisterType]; ok {
	//	updateColumns[schemas.FieldRegisterType] = data
	//}

	// user_status
	//if data, ok := conditions[schemas.FieldUserStatus]; ok {
	//	updateColumns[schemas.FieldUserStatus] = data
	//}

	// disable_time
	//if data, ok := conditions[schemas.FieldDisableTime]; ok {
	//	updateColumns[schemas.FieldDisableTime] = data
	//}

	// blacklist_time
	//if data, ok := conditions[schemas.FieldBlacklistTime]; ok {
	//	updateColumns[schemas.FieldBlacklistTime] = data
	//}

	// password_hash
	//if data, ok := conditions[schemas.FieldPasswordHash]; ok {
	//	updateColumns[schemas.FieldPasswordHash] = data
	//}

	return updateColumns
}
