// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/user-service/v1/resources/user_reg_phone.resource.v1.proto

package resourcev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserRegPhone with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserRegPhone) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserRegPhone with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserRegPhoneMultiError, or
// nil if none found.
func (m *UserRegPhone) ValidateAll() error {
	return m.validate(true)
}

func (m *UserRegPhone) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreatedTime

	// no validation rules for UpdatedTime

	// no validation rules for DeletedTime

	// no validation rules for UserId

	// no validation rules for UserPhone

	if len(errors) > 0 {
		return UserRegPhoneMultiError(errors)
	}

	return nil
}

// UserRegPhoneMultiError is an error wrapping multiple validation errors
// returned by UserRegPhone.ValidateAll() if the designated constraints aren't met.
type UserRegPhoneMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserRegPhoneMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserRegPhoneMultiError) AllErrors() []error { return m }

// UserRegPhoneValidationError is the validation error returned by
// UserRegPhone.Validate if the designated constraints aren't met.
type UserRegPhoneValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserRegPhoneValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserRegPhoneValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserRegPhoneValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserRegPhoneValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserRegPhoneValidationError) ErrorName() string { return "UserRegPhoneValidationError" }

// Error satisfies the builtin error interface
func (e UserRegPhoneValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserRegPhone.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserRegPhoneValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserRegPhoneValidationError{}
