// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schemas

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	datatypes "gorm.io/datatypes"
	gorm "gorm.io/gorm"
	time "time"
)

var _ = time.Time{}

var _ = datatypes.JSON{}

// UserRegEmailSchema UserRegEmail
var UserRegEmailSchema UserRegEmail

// NewUserRegEmail new schema
func NewUserRegEmail() *UserRegEmail {
	return &UserRegEmail{}
}

const (
	TableName = "uid_user_reg_email"

	FieldId          = "id"
	FieldCreatedTime = "created_time"
	FieldUpdatedTime = "updated_time"
	FieldDeletedTime = "deleted_time"
	FieldUserId      = "user_id"
	FieldUserEmail   = "user_email"
)

// UserRegEmail ENGINE InnoDB CHARSET utf8mb4 COMMENT '用户注册邮箱'
type UserRegEmail struct {
	Id          uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:ID" json:"id"`
	CreatedTime time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;type:time;not null;comment:最后修改时间" json:"updated_time"`
	DeletedTime int64     `gorm:"column:deleted_time;type:int;default:0;comment:删除时间" json:"deleted_time"`
	UserId      int64     `gorm:"column:user_id;index;type:int;not null;default:0;comment:uid" json:"user_id"`
	UserEmail   string    `gorm:"column:user_email;unique;type:string;size:255;not null;default:'';comment:邮箱" json:"user_email"`
}

// TableName table name
func (s *UserRegEmail) TableName() string {
	return TableName
}

// CreateTableMigrator create table migrator
func (s *UserRegEmail) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewCreateTable(migrator, migrationuitl.Version, s)
}

// DropTableMigrator create table migrator
func (s *UserRegEmail) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationInterface {
	return migrationuitl.NewDropTable(migrator, migrationuitl.Version, s)
}

// TableSQL table SQL
func (s *UserRegEmail) TableSQL() string {
	return `
create table uid_user_reg_email (
	id BIGINT unsigned auto_increment comment 'ID',
	created_time DATETIME(3) not null comment '创建时间',
	updated_time DATETIME(3) not null comment '最后修改时间',
	deleted_time BIGINT null default 0 comment '删除时间',
	user_id BIGINT not null default 0 comment 'uid',
	user_email varchar(255) not null default '' comment '邮箱',
	primary key (id),
	unique key (user_email),
	key (user_id)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COMMENT '用户注册邮箱'
`
}
