user_service:
  key: value
  snowflake:
    instance_id: "${app.project_name}/${app.server_name}/${app.server_env}/${app.version}"
    instance_name: "user_service"
    metadata:
      service: user-service

